# Array Generation

In [4]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr=np.zeros(2)# Create a 1D array of zeros
print(arr,"\n") 
arr=np.zeros((2,4)) #Create a 2D array of zeros
print(arr)

[0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.ones(3) # create a 1d array of ones
print(arr,"\n")
arr=np.ones((5,6)) # create a 2d array of ones
print(arr)

[1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
arr=np.linspace(0,10,5) # Create an array with 5 evenly spaced values between 0 and 10
print(arr,"\n")
arr=np.linspace(0,1,100) # Create an array with 100 evenly spaced values between 0 and 1
print(arr)

[ 0.   2.5  5.   7.5 10. ] 

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 

In [18]:
arr=np.eye(3) # Create a 2D identity matrix of size 3x3
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Random Generation Function 

In [21]:
arr=np.random.rand(10) # Create a 1D array of 10 random values
print(arr,"\n")
arr=np.random.rand(2, 3) # Create a 2D array of random values
print(arr)

[0.263595   0.88089249 0.27885475 0.65087683 0.61831145 0.87198554
 0.71394532 0.86519342 0.41809609 0.24551352] 

[[0.51219072 0.10996596 0.007195  ]
 [0.75635906 0.44087135 0.13976349]]


In [ ]:
arr=np.random.randn(10) # Create a 1D array of 10 random values from a standard normal distribution
print(arr,"\n")

arr=np.random.randint(10) # it generate a random integer between 0 and 10
print(arr,"\n")

arr=np.random.randint(0,10,5) # takes 3 argument low , high and the number of num you want to generate 
print(arr,"\n")

arr=np.random.randint(0, 10, size=(2, 3)) # Create a 2D array of random integers between 0 and 10
print(arr,"\n")


[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004] 

4 

[0 9 5 8 0] 

[[9 2 6]
 [3 8 2]] 



In [28]:
arr=np.random.choice([1, 2, 3, 4, 5], size=(2, 3)) # Create a 2D array of random choices from a given list
print(arr,"\n")

arr=np.random.seed(42) # Set a random seed for reproducibility
print(arr,"\n")


[[5 3 5]
 [1 2 4]] 

None 

