# Array Attributes 

In [1]:
import numpy as np

In [3]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr.shape  # Get the shape of the array

(3, 3)

In [5]:
arr.dtype  # Get the data type of the array

dtype('int64')

In [6]:
arr.ndim  # Get the number of dimensions of the array

2

In [ ]:
arr.size # Get the total number of elements in the array

9

# Array Methods


In [14]:
print(arr.min())

1


In [15]:
print(arr.max())

9


In [16]:
print(arr.sum())

45


In [20]:
print(arr.mean())

5.0


In [ ]:
print(arr.argmax())  # Get the index of the maximum element


8


In [24]:
print(arr.argmin())

0


In [18]:
np.sum(arr,axis=0)# Sum along the first axis (columns)


array([12, 15, 18])

In [19]:
np.sum(arr,axis=1) # Sum along the second axis (rows)

array([ 6, 15, 24])

# Reshaping and Resizing


In [27]:
arr=np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
arr.reshape(5,6)  # Reshape the array to 5 rows and 6 columns

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])