# Numpy Indexing and vectors

In [1]:
import numpy as np

In [2]:
arr=np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[4:9]# Slicing the array from index 4 to 8, inclusive of 4 and exclusive of 9


array([5, 7, 9])

In [8]:
arr=np.arange(1,31).reshape(5,6)  # Reshape the array to 5 rows and 6 columns
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
print(arr[0])# Accessing the first row of the array
print(arr[0][0])  # Accessing the first element of the first row
print(arr[0,3]) # Accessing the fourth element of the first row

[1 2 3 4 5 6]
1
4


In [12]:
print(arr[0:3, 1:4])  # Slicing a 2D array from rows 0 to 2 and columns 1 to 3

[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]


In [19]:
print(arr[2:],'\n')# Accessing all rows starting from the third row

print(arr[:2])# Accessing all rows up to the second row

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
print(arr[2:,3],"\n")# Accessing all rows starting from the third row and the fourth column
print(arr[2:,3:],"\n")# Accessing all rows starting from the third row and all columns from the fourth onward
print(arr[2:,1:4])# Accessing all rows starting from the third row and columns 1 to 3

[16 22 28] 

[[16 17 18]
 [22 23 24]
 [28 29 30]] 

[[14 15 16]
 [20 21 22]
 [26 27 28]]


# Boolean Indexing

In [23]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index=arr%2==0  # Creating a boolean index for even numbers
print(bool_index)

[False  True False  True False  True False  True False  True]


In [25]:
arr=arr[bool_index]  # Using the boolean index to filter the array
arr

array([12, 14, 16, 18, 20])