# Arithmetic Operation


In [1]:
import numpy as np

In [4]:
a1=np.array([1,2,4,5,6,79])
a2=np.array([1,2,3,4,5,6])
#Here size of both arrays is same, so we can perform element-wise operations
print(a1+a2)  # Element-wise addition
print(a1-a2)  # Element-wise subtraction
print(a1*a2)  # Element-wise multiplication
print(a1/a2)  # Element-wise division
print(a1//a2)  # Element-wise floor division
print(a1%a2)  # Element-wise modulus
print(a1**a2)  # Element-wise exponentiation


[ 2  4  7  9 11 85]
[ 0  0  1  1  1 73]
[  1   4  12  20  30 474]
[ 1.          1.          1.33333333  1.25        1.2        13.16666667]
[ 1  1  1  1  1 13]
[0 0 1 1 1 1]
[           1            4           64          625         7776
 243087455521]


# Broadcasting

In [ ]:
l=[12,23,45,67,89]
l+10  # This will not work as lists do not support broadcasting
# To perform the same operation with numpy, we need to convert the list to a numpy array
arr=np.array(l)
arr+10  # This will work as numpy supports broadcasting
print(arr+10)


[22 33 55 77 99]


In [ ]:
arr=np.arange(1,16).reshape(3,5)
print(arr,"\n")

arr+10


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 



array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Deep copy and Shallow copy


In [10]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
print(slice)
slice=slice*10 # we have changed the sclied elements 
slice

[1 2 3 4 5]


array([10, 20, 30, 40, 50])

In [16]:
a    # here our main or original array elements are remain same . But this thing in list is impossible

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## let's understand it in more detailed 

In [20]:
a
b=a


In [21]:
b[0]=90

In [22]:
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

from above we see that we asign a to b and now in b we change the first index element so b is changed as well as a also changed . This is called (Deep Copy).

To prevent it we will use Shallow copy , it referes to another memory location of Ram.let's do the same with shallow copy

In [35]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
b=a.copy()

In [37]:
b[0]=90
b


array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

from the above we can see the elemnt at the first index is remain same in a.