In [1]:
import numpy as np

In [8]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[5,7]])



In [10]:
A @ B

array([[15, 20],
       [35, 46]])

In [11]:
np.dot(A,B)

array([[15, 20],
       [35, 46]])

In [14]:
#Transpose 
transpose=A.T
transpose

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation 
## Stacking Array

In [22]:
a=np.array([1,4,5,6,8])
b=np.array([7,8,0,2,1])

In [23]:
np.vstack((a,b))

array([[1, 4, 5, 6, 8],
       [7, 8, 0, 2, 1]])

In [24]:
np.hstack((a,b))

array([1, 4, 5, 6, 8, 7, 8, 0, 2, 1])

In [25]:
np.column_stack((a,b))

array([[1, 7],
       [4, 8],
       [5, 0],
       [6, 2],
       [8, 1]])

# Spliting Arrya

In [27]:
c=np.arange(1,16).reshape(3,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
np.vsplit(c,3)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]])]

In [33]:
np.hsplit(c,5)

[array([[ 1],
        [ 6],
        [11]]),
 array([[ 2],
        [ 7],
        [12]]),
 array([[ 3],
        [ 8],
        [13]]),
 array([[ 4],
        [ 9],
        [14]]),
 array([[ 5],
        [10],
        [15]])]