# Valid sudoko

In [1]:
import numpy as np

In [8]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [10]:
b=s.sum(axis=0)  # Sum along the rows
for i in b:
    if i!= 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for column.")

Sudoku is valid for column.


In [13]:
c=s.sum(axis=1)
for i in c:
    if i!=45:
        print("Not valid Sudoku ")
        break
else:
    print("Valid Sudoku for row.")

Valid Sudoku for row.


In [51]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])


In [52]:
#Get the shape of the matrix
data.shape

(5, 3)

In [53]:
#Find the average age of students.
avg=data[0:,0].mean()
avg

np.float64(18.4)

In [54]:
#Extraxt math mark of all students
math_mark=data[0:,1]
math_mark

array([85, 92, 76, 65, 90])

In [55]:
#Find the highest Science mark.
higest_sci_mark=data[0:,2].max()
print(higest_sci_mark)
#find the index of the student with highest Science mark.
index_of_highest_sci_mark=data[0:,2].argmax()
index_of_highest_sci_mark

95


np.int64(2)

In [56]:
#Get details of the student who scored more than 90 in Math.

more_than_90_in_math=data[data[0:,1]>90]
more_than_90_in_math

array([[19, 92, 88]])

In [57]:
#Increase Math marks of all students by 5.
data[0:,1] +=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [58]:
#Find how many students are younger than 19.

len(data[data[0:,0]<19])

3

In [59]:
#Calculate the average marks in each subject (column-wise mean).
avg_marks = data.mean(axis=0)
avg_marks

array([18.4, 86.6, 83.2])

In [60]:
#Replace all Science marks < 75 with 0.
data[0:,2][data[0:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])